// share/templates/owned/react-ts/src/App.tsx
export function App() {
  return (
    <div className="app-shell">
      <header>
        <nav className="site-nav">
          <a href="/">Home</a>
          <span className="site-label">React + Vite</span>
        </nav>
      </header>
      <main className="page">
        <h1>Home</h1>
      </main>
    </div>
  );
}

// share/templates/seeded/vue-vite/src/App.vue
<script setup lang="{{SCRIPT_LANG}}">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <header>
    <nav class="flex gap-page bg-header p-page">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/about">About</RouterLink>
      <span class="ml-auto font-bold">Vue + Vite</span>
    </nav>
  </header>

  <main class="p-page">
    <RouterView />
  </main>
</template>
