// share/templates/overrides/frontend-bases/vue/src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <header>
    <nav class="p-5 flex gap-5 bg-green-100">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/about">About</RouterLink>
      <span class="ml-auto font-bold">Vue + Vite</span>
    </nav>
  </header>

  <main class="p-5">
    <RouterView />
  </main>
</template>

// share/templates/owned/react-js-tailwind/src/App.jsx
export function App() {
  return (
    <>
      <header>
        <nav className="flex gap-page bg-header p-page">
          <a href="/">Home</a>
          <span className="ml-auto font-bold">React + Vite</span>
        </nav>
      </header>
      <main className="p-page">
        <h1>Home</h1>
      </main>
    </>
  );
}
