// share/templates/seeded/nuxt/flat/app.vue
<template>
  <div class="flex min-h-full flex-col">
    <NuxtRouteAnnouncer />

    <header>
      <nav class="flex gap-page bg-header p-page">
        <NuxtLink to="/">Home</NuxtLink>
        <NuxtLink to="/about">About</NuxtLink>
        <span class="ml-auto font-bold">Vue + Nuxt</span>
      </nav>
    </header>

    <main class="p-page">
      <NuxtPage />
    </main>
  </div>
</template>

// share/templates/owned/react-js-tailwind/src/App.jsx
export function App() {
  return (
    <>
      <header>
        <nav className="flex gap-page bg-header p-page">
          <a href="/">Home</a>
          <span className="ml-auto font-bold">React + Vite</span>
        </nav>
      </header>
      <main className="p-page">
        <h1>Home</h1>
      </main>
    </>
  );
}
